RaphaelRegnier/rails_medlii

Gemfile, Gemfile.lock, app/controllers/users/omniauth_callbacks_controller.rb, app/models/user.rb, config/initializers/devise.rb, config/routes.rb
=> finish the facebook... I hope

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/models/user.rb, app/views/layouts/application.html.erb, config/initializers/geocoder.rb, db/migrate/20170718172317_add_coordinates_to_users.rb, db/schema.rb
=> finish geocode but i'm not sure

Gemfile, Gemfile.lock
=> maybe fix it..?

app/assets/javascripts/application.js, app/assets/stylesheets/layout/_index.scss, app/assets/stylesheets/layout/_sidebar.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_sidebar.html.erb, db/schema.rb
=> really basic stuff of sidebar

app/views/users/show.html.erb, db/migrate/20170719140854_add_photo_to_users.rb, db/schema.rb
=> Added a photo to the users table

app/assets/stylesheets/layout/_sidebar.scss, app/controllers/users_controller.rb, app/views/shared/_sidebar.html.erb, app/views/users/show.html.erb, config/initializers/geocoder.rb, db/seeds.rb
=> finish the sidebar i hope

app/assets/stylesheets/components/_avatars.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_utilities.scss, app/controllers/users_controller.rb, app/views/users/index.html.erb
added info / photo to the index view
=> Index view

app/views/users/show.html.erb
User - Show page with photo, instrument, level etc
=> added description, a bit of css and age

.byebug_history, app/models/user.rb, config/initializers/devise.rb
=> call the birthday from the facebook user and calculate the age

app/assets/stylesheets/components/_card_profile.scss
=> added card_profile again

app/controllers/application_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/users/edit.html.erb, app/views/users/new.html.erb, config/routes.rb
=> im not sure..

app/controllers/users_controller.rb, app/models/user.rb, app/views/users/_form_age.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb, db/seeds.rb
find users by instrument working.
=> Search feature

app/assets/javascripts/application.js, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_profile.scss, app/controllers/application_controller.rb, app/controllers/registrations_controller.rb, app/controllers/users_controller.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/shared/_flashes.html.erb, app/views/users/edit.html.erb, app/views/users/index.html.erb, config/initializers/simple_form.rb, config/routes.rb
=> finish update and edit profile pages

app/controllers/application_controller.rb, app/helpers/meta_tags_helper.rb, app/views/layouts/application.html.erb, config/initializers/default_meta.rb, config/meta.yml
- Open Graph meta tags are properly set ( we still have to add the cover photo)
=> Demo checklist

public/404.html, public/422.html
right error messages should show now in heroku
=> error messages fix public - 404 - 422

app/assets/stylesheets/components/_conversation.scss, app/assets/stylesheets/components/_index.scss, app/views/conversations/_form.html.erb, app/views/conversations/index.html.erb, app/views/conversations/new.html.erb
=> conversation index and new pages

app/views/conversations/index.html.erb, app/views/shared/_sidebar.html.erb, app/views/users/index.html.erb
solution for the issue with the message menu
=> solution for the message issue in heroku

app/assets/javascripts/google_maps_autocomplete.js, app/controllers/appointments_controller.rb, app/models/appointment.rb, app/views/appointments/_form.html.erb, app/views/appointments/index.html.erb, config/initializers/geocoder.rb, db/migrate/20170728135052_add_coordinates_to_appointments.rb, db/schema.rb
=> damn geocode works

public/500.html
=> change error code page to 500 not 503

config/environments/production.rb
Reverts RaphaelRegnier/rails_medlii#112
=> Revert "so hard"
